### ISSUE TITLE
Use C# 8.0 nullability annotations in the public interfaces?

### ISSUE THREAD

**Issue by Numpsy** [Analogy-LogViewer/Analogy.Interfaces#32]
Hi,

A thought I had while looking at the EventSource provider - have you considered enabling the C# 8 nullability functionality/annotations in the public interfaces?

It could be a useful way to indicate to implementers which interface fields/properties are optional and which are required?

Thanks.

**Comment by LiorBanai** [comment]
yeah It could be useful.
The reason that it was not added use due the fact that the project started as .net framework project which did not had support for nullability. I'm not sure it is fully supported by Microsoft on non .net core projects..

I'll see what happens if I force it in the csproj file..

**Comment by LiorBanai** [comment]
BTW, I created base implementation at https://github.com/Analogy-LogViewer/Analogy.LogViewer.Template that can be used to minimized to effort to implement new provider. [Serilog](https://github.com/Analogy-LogViewer/Analogy.LogViewer.Serilog) provider is already using it. and also the [regex](https://github.com/Analogy-LogViewer/Analogy.LogViewer.RegexParser) project.

I'll be moving all implementations to use the base project later on.

**Comment by Numpsy** [comment]
The base nullability bits (being able to mark reference type properties and parameters as nullable with ```?```) work with .NET builds, but there are a couple of limitations compared to the more recent runtimes:

1) The .NET runtime itself hasn't been annotated, so you don't get warnings or help for calls to that.
2) The additional attributes you can use for more advanced annotations aren't built in.

I don't think (1) is much of an issue with a lib that is mostly interface definitions, but I can't say offhand if there are cases where the attributes are useflu (Though i still think the idea is useful, and annotating interface definitions is a useful first step before doing it elsewhere)

**Comment by LiorBanai** [comment]
I'll add the annotation to the interfaces and test it against the primary application to see how it impact the warnings/errors

**Comment by LiorBanai** [comment]
It appears to be working so I'll keep those changes  and will update per project changes. Thanks for the suggestions

**Comment by LiorBanai** [comment]
Yeah I think you are correct

**Comment by LiorBanai** [comment]
closing as it implemented and released :)

**Comment by LiorBanai** [comment]
I must say this was a great suggestion. It helps me a lot even at the top level application o clean the code and remove hiding assumptions. 🙂
